sixtyone:
  # path
  label_path: /home/liubo/workplace/design/ai_challenger_pdr2018_trainingset_20181023/AgriculturalDisease_trainingset/AgriculturalDisease_train_annotations.json
  data_prefix_path: /home/liubo/workplace/design/ai_challenger_pdr2018_trainingset_20181023/AgriculturalDisease_trainingset/images
  train_json: /home/liubo/workplace/design/ai_challenger_pdr2018_trainingset_20181023/AgriculturalDisease_trainingset/train_nolevel.json
  validate_json: /home/liubo/workplace/design/ai_challenger_pdr2018_trainingset_20181023/AgriculturalDisease_trainingset/validate_nolevel.json
  test_json: /home/liubo/workplace/design/ai_challenger_pdr2018_trainingset_20181023/AgriculturalDisease_trainingset/test_nolevel.json

  # superParamter
  num_classes: 37
  keep_prob: 0.5
  epoch: 200
  use_gpu: True
  use_classes_weight: False
  lr: 0.01
  weight_decay: 0.0001
  momentum: 0.9
  optim: SGD

  #dataloader
  ckpt_path: ckpt
  batch_size: 32
  num_workers: 2
  means: [0.46322557, 0.48646197, 0.40005577]
  std: [0.1918378, 0.17038089, 0.2122889]


  #log
  logger: True
  use_tensorboard: True
  run_path: run

class:
  '0': ['苹果健康','苹果','健康','无','无','无','无']
  '1': ['苹果黑星病','苹果','疾病','黑星病','世界性苹果病害,中国的北方多省市都有此病害',
        '主要危害叶片和果实。叶片上病斑近圆形或呈放射状，初期叶上生绿褐色霉层，稍后霉层渐变为褐色至黑色。
        严重时病斑布满全叶，叶片枯焦，易早期脱落','增施有机肥，低洼积水地注意及时排水，改良土壤，以增强树势。清除初侵染源']
  '2': ['苹果灰斑病','苹果','疾病','灰斑病','苹果灰斑病全国各苹果产区都有发生',
        '叶片受害，初期产生近圆形黄褐色、边缘清晰的病斑，以后病斑变灰色。
        高温多雨季节病斑迅速扩大成不规则形，多个病斑密集或互相联合使叶片呈焦枯状','一般以化学保护为主，配合清除落叶，可以有效控制发病']
  '3': ['苹果雪松锈病','苹果','疾病','雪松锈病','城市郊区、风景旅游区附近的果园、绿化树种桧柏种植区附近的苹果树时有发生',
        '此病主要危害叶片，也能危害嫩枝、幼果和果柄，还可危害转主寄主桧柏。叶片初患病正面出现油亮的橘红色小斑点，逐渐扩大，形成圆形橙黄色的病斑，边缘红色。
        发病严重时，一张叶片出现几十个病斑','增施有机肥和磷钾肥，重施生物菌肥，科学合理修剪使树冠通风透光，雨季及时排水，清除杂草和周围侵染物，保持树盘内土质疏松，增强树势以提高树体对不良环境的抵抗力']
  '4': ['樱桃健康','樱桃','健康','无','无','无','无']
  '5': ['樱桃白粉病','樱桃','疾病','白粉病','别名白霉病、黄斑病','叶面上呈现白色粉状菌丛，秋季菌丛中呈现黑色小球状物，即病原菌的闭囊壳',
        '秋后清理果园，扫除落叶，集中烧毁']
  '6': ['玉米健康','玉米','健康','无','无','无','无']
  '7': ['玉米灰斑病','玉米','疾病','灰斑病','近年上升很快、为害较严重的病害之一','主要危害叶片。初在叶面上形成无明显边缘的椭圆形至矩圆形灰色至浅褐色病斑，后期变为褐色。病斑多限于平行叶脉之间，大小4～20×2～5(mm)',
        '选用抗病或耐病的品种、收获后及时清除病残体、加强田间管理，雨后及时排水，防止湿气滞留、药剂防治']
  '8': ['玉米锈病','玉米','疾病','锈病','华南、西南一带重要病害','主要侵染叶片，严重时也可侵染果穗、苞叶乃至雄花','施用酵素菌沤制的堆肥，增施磷钾肥，避免偏施、过施氮肥，提高寄主抗病力']
  '9': ['玉米叶斑病','玉米','疾病','叶斑病','分布在吉林、辽宁、河南等省','主要危害叶片和苞叶。病斑不规则、透光，中央灰白色，边缘褐色，上生黑色小点','及时收集病残体烧毁、药剂防治']
  '10': ['玉米花叶病毒病','玉米','疾病','花叶病毒病','玉米整个生育期均可感染，该病发生面积广，危害重','发病重的叶片发黄，变脆，易折。病叶鞘、病果穗的苞叶也能现花叶状。发病早的，病株矮化明显',
         '因地制宜，合理选用抗病杂交种或品种、在田间尽早识别并拔除病株，这是防治该病关键措施之一']
  '11': ['葡萄健康','葡萄','健康','无','无','无','无']
  '12': ['葡萄黑腐病','葡萄','疾病','黑腐病','是真菌病害，在东北、华北等地发生较多，一般危害不重','叶片发病时，初期产生红褐色小斑点，逐渐扩大成近圆形病斑，直径可达4—7厘米，中央灰白色，外缘褐色，边缘黑褐色，上面生出许多黑色小突起，排入成环状',
        '清除越冬病源、及时排水，增施有机肥']
  '13': ['葡萄轮斑病','葡萄','疾病','轮斑病','主要危害叶片','发病初期在叶面上出现红褐色圆形或不规则形病斑，后扩大为圆形或近圆形，叶面具深浅相间的轮纹，湿度大时叶背面长有浅褐色霉层',
          '认真清洁田园，加强田间管理、药剂防治']
  '14': ['葡萄褐斑病','葡萄','疾病','褐斑病','又称斑点病、褐点病、叶斑病和角斑病','褐斑病是由葡萄假尾孢菌侵染引起，主要危害叶片，侵染点发病初期呈淡褐色、不规则的角状斑点，病斑逐渐扩展，直径可达1厘米，病斑由淡褐变褐，进而变赤褐色，
  周缘黄绿色，严重时数斑连结成大斑，边缘清晰，叶背面周边模糊，后期病部枯死，多雨或湿度大时发生灰褐色霉状物','秋冬认真清园，收集病残叶烧毁、生长期间及时摘心、抹芽、实行深沟高畦，降低地下水位']
  '15': ['柑桔健康','柑桔','健康','无','无','无','无']
  '16': ['柑桔黄龙病','柑桔','疾病','黄龙病','全年都能发生，春、夏、秋梢均可出现症状，以秋、冬季症状最为明显','叶片有三种类型的黄化，即斑驳黄化、均匀黄化和缺素状黄化','严格检疫制度，杜绝病苗、病穗传入无病区和新种植区、防治柑橘木虱、微生物治理']
  '17': ['桃健康','桃','健康','无','无','无','无']
  '18': ['桃疮痂病','桃','疾病','疮痂病','又称黑星病、黑痣病，是桃树常见病害之一','初期产生褐色圆形病斑，后期病斑隆起，颜色加深','药剂防治、及时防治害虫、加强栽培管理，提高树体抗病力']
  '19': ['辣椒健康','辣椒','健康','无','无','无','无']
  '20': ['辣椒疮痂病','辣椒','疾病','疮痂病','又名细菌性斑点病，主要危害叶片、茎蔓、果实','叶片染病后初期出现许多圆形或不规则状的黑绿色至黄褐色斑点，有时出现轮纹，叶背面稍隆起，水泡状，正面稍有内凹',
        '合理轮作，露地辣椒可与葱蒜、水稻或大豆实行2--3年轮作、加强田间管理，应及时深翻土壤，加强松土、浇水、追肥，促进根系发育，提高植株抗病力']
  '21': ['马铃薯健康','马铃薯','健康','无','无','无','无']
  '22': ['马铃薯早疫病','马铃薯','疾病','早疫病','主要由链格孢属茄链格孢引起，可发生在叶片上，也可侵染块茎','叶片染病病斑黑褐色，圆形或近圆形，具同心轮纹，大小3～4mm。湿度大时，病斑上生出黑色霉层病征，即病原菌分生孢子梗和分生孢子。发病严重的叶片干枯脱落，田间植株成片枯黄',
         '选用早熟耐病品种，适当提早收获、选择土壤肥沃的高燥田块种植，增施有机肥，推行配方施肥，提高寄主抗病力']
  '23': ['马铃薯晚疫病','马铃薯','疾病','晚疫病','致病疫霉引起，导致马铃薯茎叶死亡和块茎腐烂的一种毁灭性卵菌病害','叶片染病先在叶尖或叶缘生水浸状绿褐色斑点，病斑周围具浅绿色晕圈，湿度大时病斑迅速扩大，呈褐色，并产生一圈白霉，即孢囊梗和孢子囊，尤以叶背最为明显；干燥时病斑变褐干枯，质脆易裂，不见白霉，且扩展速度减慢',
        '选用无病种薯、加强栽培管理、轮作换茬、加强田间管理']
  '24': ['草莓健康','草莓','健康','无','无','无','无']
  '25': ['草莓叶枯病','草莓','疾病','叶枯病','草莓叶枯病，主要为害叶片，是叶部的主要病害之一','叶枯病属低温、高湿性病害，多在春秋季发病，初发病时，叶面上产生紫褐色无光泽小斑点，以后逐渐扩大成不规则形病斑。
  病斑多沿主侧叶脉分布，发病重时整个叶面布满病斑，发病后期全叶黄褐色至暗褐色，直至枯死。叶柄或果柄发病后，病斑呈黑褐色，微凹陷，脆而易折',
      '发病期，及时清除病株残体，病果、病叶、病枝等。不偏施氮肥，增施磷、钾肥，培育壮苗，以提高植株自身的抗病力']
  '26': ['番茄健康','番茄','健康','无','无','无','无']
  '27': ['番茄白粉病','番茄','疾病','白粉病','番茄的普通病害,病情较轻,对生产影响不大','叶面初现白色霉点，散生，后逐渐扩大成白色粉斑，并互相连合为大小不等的白粉斑，严重时整个叶面被白粉所覆盖，像被撒上一薄层面粉','保护地栽培宜加强温湿调控，主要用粉尘法或烟雾法防治；露地栽培于发病前或病害点片发生阶段及时连续喷药控病']
  '28': ['番茄疮痂病','番茄','疾病','疮痂病','主要危害茎、叶和果实','病叶早期在叶背出现水浸状小斑，逐渐扩展近圆形或连结成不规则形黄褐色病斑，粗糙不平，病斑周围有褪绿晕圈，后期干枯质脆','初发病时用“天达2116”800倍液+“天达诺杀”1000倍液、77%多宁可湿性粉剂600倍液、70%可杀得101可湿性粉剂800倍液、新植霉素4000倍液、50%琥胶肥酸铜可湿性粉剂500倍液喷雾，每隔7-10天喷1次，连喷3次']
  '29': ['番茄早疫病','番茄','疾病','早疫病','在我国东北、华北、华东、西南等地区都有发生，其最主要特征是不论发生在果实、叶片或主茎上的病斑，都有明显的轮纹，所以又被称作轮纹病',
        '成株期叶片被害，多从植株下部叶片向上发展，初呈水浸状暗绿色病斑，扩大后呈圆形或不规则形的轮纹斑，边缘多具浅绿色或黄色的晕环，中部呈同心轮纹，潮湿时病斑上长出黑色霉层（分生孢子及分生孢子梗），严重时叶片脱落',
        '选择抗病品种、鉴于病原能有一年以上的存活期，所以要注意轮作']
  '30': ['番茄晚疫病','番茄','疾病','晚疫病','番茄重要病害之一，局部地区发生','病斑大多先从叶尖或叶缘开始，初为水浸状褪绿斑，后渐扩大，在空气湿度大时病斑迅速扩大，可扩及叶的大半以至全叶，并可沿叶脉侵入到叶柄及茎部，形成褐色条斑',
  '选用抗病品种、条件许可时可与非茄科蔬菜实行3～4年轮作']
  '31': ['番茄叶霉病','番茄','疾病','叶霉病','在番茄的叶、茎、花、果实上，都会出现的症状，但是常见的是是发生在叶片上','初期在叶片背面出现一些退绿斑，后期变为灰色或黑紫色的不规则形霉层，叶片正面在相应的部位退绿变黄，严重时，叶片常出现干枯卷缩',
          '和非茄科作物进行三年以上轮作，以降低土壤中菌源基数、选用抗病品种，严把育苗关、每年更换一次棚室薄膜，使用无滴膜，经常清除膜上灰尘']
  '32': ['番茄斑点病','番茄','疾病','斑点病','主要危害叶片','初生绿褐色水浸状小斑点，后扩大，周缘黑褐色，中间灰褐色，大小2～3毫米，病斑圆形或近圆形，病斑周围形成不规则形黄化区，后期病斑中间穿孔，叶片黄化枯死或脱落',
      '采用配方施肥技术，施用酵素菌沤制的堆肥或充分腐熟的有机肥，合理灌溉，避免浇水过量，棚室浇水改在上午，适时放风，防止湿度过高；注意田间卫生，及时收集病残物烧毁']
  '33': ['番茄斑枯病','番茄','疾病','斑枯病','又称鱼目斑病、斑点病、白星病，为番茄叶部常见病害,南北各地均有分布','叶片染病，先从下部老叶片开始，初期背出现水渍状小圆斑，后叶两面都出现圆形和近圆形病斑，病斑边缘深褐色，中央灰白色，凹陷，病部表面散生稀疏、隆起的小黑点','从无病株上选留种子、重病地与非茄科作物实行3～4年轮作，最好与豆科或禾本科作物轮作']
  '34': ['番茄红蜘蛛损伤','番茄','疾病','红蜘蛛损伤','近些年来，红蜘蛛已成为危害园林花卉树木的重要害虫之一','主要危害植物的叶、茎、花等，刺吸植物的茎叶，使受害部位水分减少，表现失绿变白，叶表面呈现密集苍白的小斑点，卷曲发黄。严重时植株发生黄叶、焦叶、卷叶、落叶和死亡等现象',
        '加强管理，做好农业防治： 及时清除温室内残株败叶，内部及外部周边杂草，来消灭部分虫源和红蜘蛛的中间寄主;适时使用化学农药，及时防治']
  '35': ['番茄黄化曲叶病毒病','番茄','疾病','黄化曲叶病毒病','番茄黄化曲叶病毒病为中国番茄黄化曲叶病毒(Tomato yellow leaf curl virus，TYLCV)，属于双生病毒科','染病番茄植株矮化，生长缓慢或停滞，顶部叶片常稍褪绿发黄、变小，叶片边缘上卷，叶片增厚，叶质变硬，叶背面叶脉常显紫色','培育无病无虫苗是关键、重防烟粉虱']
  '36': ['番茄花叶病毒病','番茄','疾病','花叶病毒病','常见病毒，对产量影响甚微','在叶片上发生轻微的花叶或绿色深浅不匀的斑驳，植株生长发育正常，株高与健株无异，叶片不变小，不畸形，植株不矮化','采收完后及时清除病残体，在远离菜地、水源的地方处烧毁或挖坑深埋、因地制宜，合理选用抗病品种']